# config file for spellcheck action
matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    encoding: utf-8
    wordlists:
    - .github/config/.wordlist.txt
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - '**/**/*.md'
  default_encoding: utf-8
- name: reST
  sources:
  - '**/**/*.rst'
  dictionary:
    wordlists:
      - .github/config/.wordlist.txt
  pipeline:
  - pyspelling.filters.text:
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      # Ignore text between inline back ticks
      - open: '(div style|iframe).*'
        close: '\n'
      - open: '(- )?(?P<open>`+)'
        close: '(?P=open)'
      - open: ':figure:.*'
        close: '\n'
      # Ignore reStructuredText roles
      - open: ':(?:(class|file|func|math|ref|octicon)):`'
        content: '[^`]*'
        close: '`'
      - open: ':width:'
        close: '$'
      # Exclude raw directive
      - open: '\.\. (raw|grid-item-card|galleryitem|includenodoc)::.*$\n*'
        close: '\n'
      # Ignore reStructuredText literals
      - open: '::$'
        close: '(?P<literal>(?:((?P<indent>[ ]+).*$)|(\n))+)'
      # Ignore reStructuredText hyperlinks
      - open: '\s'
        content: '\w*'
        close: '_'
      # Ignore hyperlink in the DDP tutorials
      - open: '`.*'
        close: '`__'
      # Ignore reStructuredText header ---
      - open: '^'
        content: '--*'
        close: '$'
      # Ignore reStructuredText header '''
      - open: '^'
        content: '''''*'
        close: '$'
      # Ignore reStructuredText block directives
      - open: '\.\. (code-block|math)::.*$\n*'
        content: '(?P<first>(^(?P<indent>[ ]+).*$\n))(?P<other>(^([ \t]+.*|[ \t]*)$\n)*)'
        close: '(^(?![ \t]+.*$))'
      - open: '\.\. (raw)::.*$\n*'
        close: '^\s*$'
      # Ignore reStructuredText substitution definitions
      - open: '^\.\. \|[^|]+\|'
        close: '$'
      # Ignore reStructuredText substitutions
      - open: '\|'
        content: '[^|]*'
        close: '\|_?'
      # Ignore reStructuredText toctree
      - open: '\.\.\s+toctree::'
        close: '(?P<toctree>(?:((?P<indent>[ ]+).*$)|(\n))+)'
      # Ignore directives
      - open: '\.\.\s+(image|include|only)::'
        close: '$'
